### ISSUE TITLE
alter_id from a environment variable 

### ISSUE THREAD

**Issue by juanpabloaj** [0x27/imgurscrot#2]
to use the script is necessary change the client_id, like say in this line

https://github.com/0x27/imgurscrot/blob/master/imgurscrot.py#L18

maybe you can get the client_id from a environment variable, like I make in slacker-cli

https://github.com/juanpabloaj/slacker-cli/blob/master/slacker_cli/__init__.py#L46

**Comment by 0x27** [comment]
Good point, I must admit, I did accidentally commit my own client_id there. I'll rectify that post haste :)

**Comment by 0x27** [comment]
Fixed: https://github.com/0x27/imgurscrot/commit/aa87c0ccb8182b9530ea00256c9cf46cfb0edc16
Many thanks :) This 24 hour hackathon is taking its toll, this is the second time I have hardcoded and committed an API key today!

**Comment by juanpabloaj** [comment]
maybe in the readme file you need add the name of environment variable and how set this
